config/routes.rb
HistoricStockQuotes::Application.routes.draw do
  get "stocks/:symbol" => "stocks#show", as: 'stock'
  get "stocks/:symbol/history/:start_date/:end_date" => "stocks#history",  as: 'history'
end

app/models/stock.rb
require 'stock_quote'

class Stock
  def self.find(symbol)
    StockQuote::Stock.quote(symbol)
  end

  def self.stock_history(symbol, start_date, end_date)
    StockQuote::Stock.history(symbol, start_date, end_date).map { |stock|
      ["#{stock.date} 00:00:00 UTC", stock.close]
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def show
    @stock = Stock.find(params[:symbol])
    @stocks = Stock.stock_history(params[:symbol], DateTime.now - 7, DateTime.now)
  end

  def history
    @stocks = Stock.stock_history(params[:symbol], params[:start_date], params[:end_date])
    @percent_change = (@stocks.first[1] - @stocks.last[1])/@stocks.last[1] * 100
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HistoricStockQuotes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_history.html.erb
<%= line_chart @stocks %>

app/views/stocks/history.html.erb
<%= render 'history' %>

<h3>Percent Change</h3>
<p>
  <%= number_to_percentage(@percent_change, precision: 2) %>
</p>

<%= link_to "Stock Detail", stock_path(params[:symbol]) %>

app/views/stocks/show.html.erb
<h1><%= @stock.name %> (<%= @stock.symbol %>)</h1>
<h2><%= @stock.stock_exchange %></h2>

<h3>Price</h3>
<p>
  <%= number_to_currency(@stock.last_trade_price_only) %> (<%= @stock.percent_change %>)
</p>

<h3>Open</h3>
<p>
  <%= number_to_currency(@stock.open) %>
</p>

<h3>Previous Open</h3>
<p>
  <%= number_to_currency(@stock.previous_close) %>
</p>

<div id="history-form" class="stock-history" style="display:none;">
  <%= render 'history' %>
</div>

<%= link_to_modal "Historic Price", "#history-form", :class=>"button" %>

<%= link_to "Year-To-Date History", history_path(@stock.symbol, Time.now.strftime("%Y-01-01"), Time.now.strftime("%Y-%m-%d")) %>